AUGMENTATION: False             # params.yaml
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 64
INCLUDE_TOP: False
EPOCHS: 20
LEARNING_RATE: 0.08
CLASSES: 2  # adjust depending on how many disease categories you have
WEIGHTS: imagenet
